package login;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import login.loginFram;
import java.text.*;
import java.util.ArrayList;
import java.util.Date;
/**
 *
 * @author arthe
 */
public class fillPage extends javax.swing.JFrame {

    /**
     * Creates new form fillPage
     */
    public fillPage() {
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);//setFullscreen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtRecord = new javax.swing.JLabel();
        jtMachineNumber = new javax.swing.JLabel();
        jtDevicename = new javax.swing.JLabel();
        jtLocation = new javax.swing.JLabel();
        jc_Device = new javax.swing.JComboBox<>();
        jc_Machinenumber = new javax.swing.JComboBox<>();
        jc_Location = new javax.swing.JComboBox<>();
        jTF_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtSelect = new javax.swing.JTextField();
        jb_Submit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtRecord.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jtRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jtRecord.setText("Record of equipment inspection");

        jtMachineNumber.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtMachineNumber.setText("Machine number");

        jtDevicename.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtDevicename.setText("Device name");

        jtLocation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtLocation.setText("Location");

        jc_Device.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Projector", "Air", "Smart Ticket", " " }));
        jc_Device.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_DeviceActionPerformed(evt);
            }
        });

        jc_Machinenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_MachinenumberActionPerformed(evt);
            }
        });

        jc_Location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theater1", "Theater2", "Theater3", "Theater4", "Theater5", " " }));
        jc_Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_LocationActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Investigator's name");

        jb_Submit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jb_Submit.setText("SUBMIT");
        jb_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jb_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jc_Location, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtDevicename)
                                        .addComponent(jtMachineNumber)
                                        .addComponent(jtLocation)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(jTF_name, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jc_Device, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jc_Machinenumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jtSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jtRecord)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtLocation)
                    .addComponent(jc_Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDevicename)
                    .addComponent(jc_Device, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtMachineNumber)
                    .addComponent(jc_Machinenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jtSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jb_Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jc_MachinenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_MachinenumberActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_jc_MachinenumberActionPerformed

    private void jc_DeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_DeviceActionPerformed
        // TODO add your handling code here
        if(jc_Device.getSelectedItem().equals("Projector")){
            jc_Machinenumber.removeAllItems();
            jc_Machinenumber.setSelectedItem(null);
            jc_Machinenumber.addItem("aaaa");
            jc_Machinenumber.addItem("bbbb");
        }else if(jc_Device.getSelectedItem().equals("Air")){
            jc_Machinenumber.removeAllItems();
            jc_Machinenumber.setSelectedItem(null);
            jc_Machinenumber.addItem("cccc");
            jc_Machinenumber.addItem("dddd");
        }else if(jc_Device.getSelectedItem().equals("Smart Ticket")){
            jc_Machinenumber.removeAllItems();
            jc_Machinenumber.setSelectedItem(null);
            jc_Machinenumber.addItem("eee");
            jc_Machinenumber.addItem("fff");
        }
        String selectTheator = jc_Location.getSelectedItem().toString();
        String selectItem = jc_Device.getSelectedItem().toString();
        String selectMacineNumber = jc_Machinenumber.getSelectedItem().toString();
        jtSelect.setText(selectTheator+"\t"+selectItem+"\t"+selectMacineNumber);
    }//GEN-LAST:event_jc_DeviceActionPerformed

    private void jc_LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_LocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_LocationActionPerformed

    private void jb_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_SubmitActionPerformed
        // TODO add your handling code here:
        dataPage DP = new dataPage();
        DP.show();//show datapage
        
        dispose();//close fillpage when datapage show
    }//GEN-LAST:event_jb_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fillPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fillPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTF_name;
    private javax.swing.JButton jb_Submit;
    private javax.swing.JComboBox<String> jc_Device;
    private javax.swing.JComboBox<String> jc_Location;
    private javax.swing.JComboBox<String> jc_Machinenumber;
    private javax.swing.JLabel jtDevicename;
    private javax.swing.JLabel jtLocation;
    private javax.swing.JLabel jtMachineNumber;
    private javax.swing.JLabel jtRecord;
    private javax.swing.JTextField jtSelect;
    // End of variables declaration//GEN-END:variables
}
